schema_version: 1

context:
  python_min: "3.12"
  version: "0.3.2"

package:
  name: pytensor-distributions
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pytensor-distributions/pytensor_distributions-${{ version }}.tar.gz
  sha256: 43139e337c45185959b8c19cdfadb5eb0a6ee8dd34b7d8b77630119eb6e4c055

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.0
    - pytensor >=3.0.0,<4.0.0

tests:
  - python:
      imports:
        - pytensor_distributions
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: PyTensor powered distributions.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/pymc-devs/pytensor-distributions
  documentation: https://pytensor-distributions.readthedocs.io
  repository: https://github.com/pymc-devs/pytensor-distributions

extra:
  recipe-maintainers:
    - aloctavodia
    - ricardov94
    - maresb
