schema_version: 1

context:
  python_min: "3.11"
  version: "0.2.0"

package:
  name: pytensor-distributions
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pytensor-distributions/pytensor_distributions-${{ version }}.tar.gz
  sha256: 05f34156fb4b63ded816a01f39fe85ed93160b2a2ffcf5d78a32954fa74535fb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.0
    - pytensor >=2.32.0

tests:
  - python:
      imports:
        - pytensor_distributions
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: PyTensor powered distributions.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/pymc-devs/pytensor-distributions
  documentation: https://pytensor-distributions.readthedocs.io
  repository: https://github.com/pymc-devs/pytensor-distributions

extra:
  recipe-maintainers:
    - aloctavodia
    - ricardov94
    - maresb
